[package]
name = "nuklear_rs"
version = "0.1.0"
authors = ["George Burton <burtonageo@gmail.com>"]
build = "build.rs"

[dependencies]
bitflags = "0.6"

[build-dependencies]
gcc = "0.3"

[features]
default = []
rust_allocator = []
io = []
malloc_allocator = []
