[package]
name = "nuklear_rs"
version = "0.1.0"
authors = ["George Burton <burtonageo@gmail.com>"]
build = "build.rs"

[dependencies]
bindgen_plugin = { git = "https://github.com/crabtw/rust-bindgen.git", optional = true }
bitflags = "0.6"

[build-dependencies]
gcc = "0.3"

[features]
use_bindgen_plugin = []
default = ["rust_allocator"]
rust_allocator = []
io = []
malloc_allocator = []
vertex_buffers = []
font_baking = []
